import { cp, mkdir, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";

export function offlineStyles(css) {
  // Google Fonts URLs contain semicolons in their weight lists (500;600).
  // Match the complete url(...) import, not the first semicolon in its URL.
  const googleFontsImport = /@import\s+url\(\s*(?:"https:\/\/fonts\.googleapis\.com\/[^\"]*"|'https:\/\/fonts\.googleapis\.com\/[^']*'|https:\/\/fonts\.googleapis\.com\/[^\s)]*)\s*\)\s*;\s*/gi;
  const local = css.replace(googleFontsImport, "");
  if (/(?:@import\s+["']|url\(\s*["']?)(?:https?:)?\/\//i.test(local)) {
    throw new Error("Desktop CSS still contains a remote resource. Bundle it locally first.");
  }
  // Tailwind excludes gitignored .generated by default. Explicitly scan the copied game.
  return local.replace('@import "tailwindcss";', '@import "tailwindcss";\n@source "./";\n@source "../../renderer.tsx";');
}

export async function prepare(repositoryRoot, desktopRoot) {
  const output = path.join(desktopRoot, ".generated");
  const required = ["src/game", "src/components/nexus-app.tsx", "src/styles.css", "public/textures"];
  // Validate before clearing a previous successful generated snapshot.
  for (const relative of required) {
    await stat(path.join(repositoryRoot, relative));
  }
  const styles = offlineStyles(await readFile(path.join(repositoryRoot, "src/styles.css"), "utf8"));
  await rm(output, { recursive: true, force: true });
  await mkdir(path.join(output, "src/components"), { recursive: true });
  await mkdir(path.join(output, "public"), { recursive: true });
  await cp(path.join(repositoryRoot, "src/game"), path.join(output, "src/game"), { recursive: true, dereference: true });
  await cp(path.join(repositoryRoot, "src/components/nexus-app.tsx"), path.join(output, "src/components/nexus-app.tsx"));
  await cp(path.join(repositoryRoot, "public/textures"), path.join(output, "public/textures"), { recursive: true, dereference: true });
  await writeFile(path.join(output, "src/styles.css"), styles);
  const hash = createHash("sha256");
  async function hashFiles(directory) {
    for (const entry of (await readdir(directory, { withFileTypes: true })).sort((a, b) => a.name.localeCompare(b.name))) {
      const filename = path.join(directory, entry.name);
      if (entry.isDirectory()) await hashFiles(filename);
      else {
        hash.update(path.relative(output, filename).split(path.sep).join("/"));
        hash.update(await readFile(filename));
      }
    }
  }
  await hashFiles(output);
  await writeFile(path.join(output, "public/build-info.json"), JSON.stringify({ sourceSHA256: hash.digest("hex"), edition: "desktop" }, null, 2));
  return output;
}

async function writeNotices(desktopRoot, output) {
  const notices = ["Nexus Arena Desktop - bundled library notices\n"];
  for (const name of ["react", "react-dom", "scheduler", "three", "lucide-react", "zustand"]) {
    const directory = path.join(desktopRoot, "node_modules", name);
    const metadata = JSON.parse(await readFile(path.join(directory, "package.json"), "utf8"));
    const licenses = (await readdir(directory)).filter((filename) => /^(licen[sc]e|copying)(\.|$)/i.test(filename));
    if (!licenses.length) throw new Error(`Missing license text for ${name}; review it before packaging.`);
    notices.push(`\n=== ${name} ${metadata.version} ===\n`);
    for (const filename of licenses) notices.push(await readFile(path.join(directory, filename), "utf8"));
  }
  await writeFile(path.join(output, "public/THIRD-PARTY-NOTICES.txt"), notices.join("\n"));
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const desktopRoot = fileURLToPath(new URL("..", import.meta.url));
  prepare(path.resolve(desktopRoot, ".."), desktopRoot)
    .then(async (output) => {
      await writeNotices(desktopRoot, output);
      console.log("Desktop snapshot ready. Web source files were not changed.");
    })
    .catch((error) => { console.error(error.message); process.exitCode = 1; });
}
